apiVersion: v1
kind: ServiceAccount
metadata:
  name: sglang-sa
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sglang-qwen-singlenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sglang-qwen
  serviceName: "sglang-qwen"
  template:
    metadata:
      labels:
        app: sglang-qwen
    spec:
      serviceAccountName: sglang-sa
      hostNetwork: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: reflection-g4-pool
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: sglang-container
        image: docker.io/lmsysorg/sglang:dev-cu13
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add: ["IPC_LOCK", "SYS_PTRACE"]
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
        - name: FLASHINFER_DISABLE_VERSION_CHECK
          value: "1"
        - name: NCCL_NCHANNELS
          value: "16"
        - name: NCCL_DEBUG
          value: INFO
        - name: NCCL_SOCKET_IFNAME
          value: "eth0,eth1"
        - name: NCCL_IB_DISABLE
          value: "1"
        - name: NCCL_P2P_LEVEL
          value: "SYS"
        - name: NCCL_SOCKET_NTHREADS
          value: "8"
        - name: NCCL_NSOCKS_PERTHREAD
          value: "8"
        - name: OMP_NUM_THREADS
          value: "24"
        - name: SGLANG_SET_CPU_AFFINITY
          value: "1"
        - name: SAFETENSORS_FAST_GPU
          value: "1"
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: "expandable_segments:True"
        command: ["python3", "-m", "sglang.launch_server"]
        args:
        - --model-path
        - Qwen/Qwen3.5-397B-A17B-FP8
        - --tp
        - "8"
        - --reasoning-parser
        - qwen3
        - --tool-call-parser
        - qwen3_coder
        - --chunked-prefill-size
        - "4096"
        - --max-prefill-tokens
        - "32768"
        - --enable-mixed-chunk
        - --enable-fused-qk-norm-rope
        - --enable-fused-moe-sum-all-reduce
        - --enable-flashinfer-allreduce-fusion
        - --enforce-piecewise-cuda-graph
        - --mem-fraction-static
        - "0.8"
        - --disable-radix-cache
        - --host
        - 0.0.0.0
        - --port
        - "30000"
        resources:
          limits:
            nvidia.com/gpu: "8"
        volumeMounts:
        - { name: dshm,           mountPath: /dev/shm }
        - { name: hf-cache,       mountPath: /root/.cache/huggingface }

      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 100Gi
      - name: hf-cache
        hostPath:
          path: /tmp/huggingface
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: sglang-qwen-service
spec:
  type: NodePort
  selector:
    app: sglang-qwen
  ports:
  - name: serving
    port: 30000
    targetPort: 30000
