apiVersion: batch/v1
kind: Job
metadata:
  name: agentic-benchmark-job-hicahche-cpu-pool-low-load
spec:
  template:
    spec:
      nodeSelector:
        workload: benchmark-client
      containers:
      - name: benchmark
        image: us-central1-docker.pkg.dev/northam-ce-mlai-tpu/shivaji-rflx-docker-repo/agentic-benchmark:low-load
        args: ["http://sglang-serving-on-master:8000", "--parallelism", "64", "--timeout", "1800.0"]
      restartPolicy: Never
