apiVersion: v1
kind: ServiceAccount
metadata:
  name: sglang-sa
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: distributed-sglang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributed-sglang
  serviceName: "sglang-master-pod"
  template:
    metadata:
      labels:
        app: distributed-sglang
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "12"
        gke-gcsfuse/memory-limit: "32Gi"
        networking.gke.io/default-interface: 'eth0'
        networking.gke.io/interfaces: |
          [
            {"interfaceName": "eth0", "network": "default"},
            {"interfaceName": "eth1", "network": "h200-network-gvnic"},
            {"interfaceName": "eth2", "network": "h200-network-rdma-1"},
            {"interfaceName": "eth3", "network": "h200-network-rdma-2"},
            {"interfaceName": "eth4", "network": "h200-network-rdma-3"},
            {"interfaceName": "eth5", "network": "h200-network-rdma-4"},
            {"interfaceName": "eth6", "network": "h200-network-rdma-5"},
            {"interfaceName": "eth7", "network": "h200-network-rdma-6"},
            {"interfaceName": "eth8", "network": "h200-network-rdma-7"},
            {"interfaceName": "eth9", "network": "h200-network-rdma-8"}
          ]
    spec:
      serviceAccountName: sglang-sa
      containers:
      - name: sglang-container
        image: docker.io/lmsysorg/sglang:v0.5.10.post1
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - |
          python3 -m sglang.launch_server \
              --model-path /models \
              --tensor-parallel-size 8 \
              --pipeline-parallel-size 2 \
              --nnodes 2 \
              --node-rank $POD_INDEX \
              --port 8000 \
              --dist-init-addr distributed-sglang-0.sglang-master-pod:5000 \
              --trust-remote-code \
              --kv-cache-dtype fp8_e5m2 \
              --reasoning-parser kimi_k2 \
              --tool-call-parser kimi_k2 \
              --mem-fraction-static 0.88 \
              --chunked-prefill-size 8192 \
              --cuda-graph-max-bs 256 \
              --max-running-requests 1024 \
              --host 0.0.0.0

        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
        - name: POD_INDEX
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: NCCL_DEBUG
          value: INFO
        - name: NCCL_IB_DISABLE
          value: "0"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/gib/lib64:/usr/local/nvidia/lib64"
        - name: NCCL_NET
          value: "gIB"
        - name: USE_GPU_DIRECT
          value: "true"
        - name: NCCL_SOCKET_IFNAME
          value: "eth0"
        - name: NCCL_PXN_C2C
          value: "1"
        - name: NCCL_IB_MERGE_VFS
          value: "1"
        - name: NCCL_IB_ADAPTIVE_ROUTING
          value: "1"
        - name: NCCL_IB_GID_INDEX
          value: "3"
        - name: NCCL_IB_TC
          value: "52"
        - name: NCCL_IB_FIFO_TC
          value: "84"
        - name: NCCL_IB_QPS_PER_CONNECTION
          value: "4"
        - name: NCCL_NCHANNELS_PER_NET_PEER
          value: "1"
        - name: NCCL_P2P_NET_CHUNKSIZE
          value: "262144"
        - name: NCCL_TUNER_CONFIG_PATH
          value: "/usr/local/gib/configs"
        resources:
          limits:
            nvidia.com/gpu: "8"
          requests:
            nvidia.com/gpu: "8"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /root/.cache/huggingface
          name: hf-cache
        - mountPath: /models
          name: models
          readOnly: true
        - mountPath: /usr/local/nvidia
          name: nvidia
        - mountPath: /usr/local/gib
          name: gib
        securityContext:
          privileged: true  
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: h200-tcpx-pool
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 32Gi
        name: dshm
      - name: hf-cache
        emptyDir: {}
      - name: models
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: pallaviam-sglang-kimi-us-east5
            mountOptions: "implicit-dirs,only-dir=kimi-k2.6,file-cache:max-size-mb:900000,file-cache:enable-parallel-downloads:true,file-cache:parallel-downloads-per-file:16,file-cache:max-parallel-downloads:-1,file-cache:download-chunk-size-mb:50,file-cache:cache-file-for-range-read:true,metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1"
      - name: nvidia
        hostPath:
          path: /home/kubernetes/bin/nvidia
      - name: gib
        hostPath:
          path: /home/kubernetes/bin/gib
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-master-pod
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: distributed-sglang
    apps.kubernetes.io/pod-index: "0"
  ports:
  - name: dist-port
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-serving-on-master
spec:
  type: NodePort
  selector:
    app: distributed-sglang
    apps.kubernetes.io/pod-index: "0"
  ports:
  - name: serving
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 8080
    targetPort: 8080
